[package]
name = "sift-mgmt"
description = "ATOM-XML management REST client for Azure Service Bus namespaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quick-xml.workspace = true
reqwest.workspace = true
roxmltree.workspace = true
sift-core.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
uuid.workspace = true

[lints]
workspace = true
